### ISSUE TITLE
[8pt] GNURadio SINK to OpenCMW worker for n (Sinus-)signals

### ISSUE THREAD

**Issue by johannaheuser** [fair-acc/pulsed-power-ml#19]
This shall be the final API,
Unit tests are included,
n signals x 5 time sampling factors need to be managed as the client may ask arbitrary combinations of signals.
Mapping between different signals and ring buffers must be implemented. If signals are not compatible or not existent, an intelligent exception must be thrown.

**Tasks**

- [x] Implement for n=1 and single sample rate
    - [x] gr-time sink providing a callback function called from `work`
    - [x] opencmw worker
        - [x] RingBuffer stores chunks of data
            - [x] tryPublish called from `work` callback
                - [x] annotate chunks with current timestamp
            - [x] periodic task calls poller and accumulates all chunks into `Acquisition` object and calls notify
    - [x] unit tests with libhttp::client tests subscription to a sample source
- [ ] Implement for multiple sinks and multiple sampling rates
    - [x] gr-sinks register themselves at singleton registry with the signal name provided to the sink block
    - [x] opencmw worker registers callback functions to all sinks and publishes their data via dedicated ring buffers
    - [ ] each sink should provide multiple(e.g. 5) downsampled sampling frequencies https://github.com/fair-acc/gr-digitizers/blob/main/include/digitizers/cascade_sink.h#L21 https://github.com/fair-acc/gr-digitizers/blob/main/lib/block_aggregation_impl.h https://github.com/fair-acc/gr-digitizers/blob/main/lib/block_aggregation_impl.cc
    - [ ] channel names consist among others of the signal name configured in the sink block and the sample rate, examples here: https://git.gsi.de/acc/specs/generic-daq/-/tree/DAQ_API#filters
    - [ ] detect if requested signals in one subscription have different sample rates
    - [ ] Replace poller by "multi poller" which only advances all RingBuffers at the same time.
    - [ ] Testcases for multiple channels/sampling rates

**Findings**

-  `MultiArray` compilation error
- Subscription and query parameters matching
