### ISSUE TITLE
[3pt,5pt] REST client for n signals, final time-domain API

### ISSUE THREAD

**Issue by johannaheuser** [fair-acc/pulsed-power-ml#20]
Productive code with unit test coverage and full QA,
Packaging to manage long polling API,
No inspection of the DataSet interface

API definition: https://git.gsi.de/acc/specs/generic-daq#time-domain-fec-acquisition-properties-user-interface
use `Annotated` interface

**Tasks**
- [x] Implement time-domain DAQ API object
- [x] Deserialize MultiArrays
- [x] Destride strided arrays
- [ ] REST client for n signals
- [x] Visualization of n signals
