### ISSUE TITLE
[1pt] Visualize 1 Sinus-signal with 1 subscription in dashboard

### ISSUE THREAD

**Issue by johannaheuser** [fair-acc/pulsed-power-ml#21]
**Tasks**

- [ ] Replace nlohmann deserializer by opencmw deserializer
    - [x] Fetch ranges-v3 library in cmake when using clang
    - [x] Add serialiser include target (cmake)
- [x] Adapt nlohmann json deserialization to DAQ API 
- [x] Adapt buffer to DAQ API
- [x] Adapt ImPlot::PlotLine
    - [x] Format time axis to date/time
    - [x] Convert unix timestamp to microseconds

**Findings** 

- `mp-units` (required for opencmw build) requires `range-v3` if it is compiled with clang < 14 which is the case with emscripten compiler [(https://emscripten.org/docs/tools_reference/emcc.html)](https://emscripten.org/docs/tools_reference/emcc.html).
- when using clang, dependency type resolving issues occur (during library includes, e.g. ambiguous symbols)
- `ImPlot::PlotLine` only supports homogeneous data types (e.g. int64_t/int64_t or float/float), but int64_t/float is not supported. 
- `ImPlot` date/time axis formatting supports unix timestamps down to microsecond precision level using double [https://github.com/epezent/implot/issues/48#issuecomment-687895607](https://github.com/epezent/implot/issues/48#issuecomment-687895607). Timestamps in the time-domain DAQ API are given in nanosecond. For now, we will plot time in microsecond resolution as a max. 50 Hz sample rate results in  20 millisecond time intervals.
