### ISSUE TITLE
[3pt,10pt] Visualize n  Sinus-signals with m subscription in dashboard

### ISSUE THREAD

**Issue by johannaheuser** [fair-acc/pulsed-power-ml#22]
**Tasks**

- [x] Fix sample drops
- [x] Implement multiple subscriptions
- [x] list of subscriptions
- [x] provide an additional query parameter with the last updated time stamp it received (e.g.` lastTimeStamp=...`)
- [x] periodic polling (ideally in a separate browser thread)
- [ ] Global CMakeLists.txt definition to simplify the build process

**Findings**

-  [https://github.com/fair-acc/opencmw-cpp/issues/231](https://github.com/fair-acc/opencmw-cpp/issues/231)
-  Emscripten Wasm Worker API fails to compile: [https://github.com/emscripten-core/emscripten/issues/17213](https://github.com/emscripten-core/emscripten/issues/17213)
